name: Node.js CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    test:
        env:
            CI: true

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x, 15.x, 16.x, 17.x]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm ci
            - run: npm run lint
            - run: npm run test-ci

    build:
        needs: test
        env:
            CI: true
            IMAGE_NAME: juanjofranco/ttn-hooks

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 16
              uses: actions/setup-node@v1
              with:
                  node-version: 16.x
            - run: npm ci
            - run: npm run build --if-present

            - name: Docker Build and Publish
              if: github.ref == 'refs/heads/main'
              uses: docker/build-push-action@v1
              with:
                  username: ${{ secrets.DOCKER_USER }}
                  password: ${{ secrets.DOCKER_TOKEN }}
                  repository: ${{ env.IMAGE_NAME }}
                  tag_with_ref: true
                  tag_with_sha: true
